name: 1. Invalidate CloudFront distributions
#This workflow is used to invalidate cloudfront distributions when updates to html files are made

on:
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"

permissions:
  id-token: write # This is required for aws oidc connection
  contents: write # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR

concurrency:
  group: deployment_sequence
  cancel-in-progress: true

jobs:
  connect_and_invalidate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: GitHub-OIDC
        role-duration-seconds: 1200
    
    - name: Create budget
      run: aws budgets create-budget --acount-id ${{ secrets.AWS_ACCOUNT }} --budget file://budget.json --notifications-with-subscribers file://notification.json
