name: 1. Configure and Test Actions

on:
  push:
    paths:
      - 'cfn/s3bucket.yml'
      - '.github/workflows/config.yml'
      - 'cdk/cdk.ts'
    branches: [ "main", "dev-cdk" ]

env:
  AWS_REGION: "us-east-1"
  BUCKET_NAME: "devopsdsm-s3-bucket"

permissions:
  id-token: write # This is required for aws oidc connection
  contents: write # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR

concurrency:
  group: deployment_sequence
  cancel-in-progress: true

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: GitHub-OIDC
        role-duration-seconds: 1200
        
    - name: Install cdk npm dependencies
      run: npm ci
      working-directory: cdk
      
    - name: cdk diff
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'diff'
        working_dir: 'cdk'

    - name: cdk synth
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'synth'
        working_dir: 'cdk'

    - name: cdk synth
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'bootstrap'
        working_dir: 'cdk'

    - name: cdk deploy
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: 'deploy'
        working_dir: 'cdk'